export type MissionProps = {
    area: string;
    bookmarks: number;
    category_id: number;
    category_title: string;
    comments: number;
    description: string;
    emoji: string;
    ended_at: string | null;
    event_type: string | null;
    feed_id: number | null;
    feeds_count: number;
    gender: string;
    has_check: number;
    id: number;
    is_available: number;
    is_bookmark: number;
    is_event: number;
    is_ground: number;
    is_ocr: number;
    is_old_event: number;
    mission_stat_id: number;
    mission_stat_user_id: number;
    nickname: string;
    place_address: string | null;
    place_description: string | null;
    place_image: string | null;
    place_title: string | null;
    place_url: string | null;
    product_brand: string | null;
    product_id: number | null;
    product_image: string | null;
    product_price: number | null;
    product_title: string | null;
    product_type: string | null;
    product_url: string | null;
    profile_image: string | null;
    started_at: string | null;
    success_count: number | null;
    thumbnail_image: string | null;
    title: string;
    today_upload: number;
    user_id: number;
  };